# Generated by Django 6.0.3 on 2026-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='avaliacoes/')),
                ('link', models.URLField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
