# Generated by Django 6.0.3 on 2026-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produtoimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='produto',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Digite no formato: 5511999999999 (sem espaço ou hifém)', max_length=20, null=True),
        ),
    ]
