# Generated by Django 6.0.3 on 2026-04-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço com desconto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tem_desconto',
            field=models.BooleanField(default=False, verbose_name='Tem desconto?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Digite no formato: 5511999999999 (sem espaço ou hífen)', max_length=20, null=True),
        ),
    ]
