# Generated by Django 6.0.3 on 2026-04-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_preco_desconto_produto_tem_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='prazo_dias_uteis',
            field=models.PositiveIntegerField(blank=True, help_text='Exemplo: 8', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.PositiveIntegerField(blank=True, help_text='Exemplo: 100', null=True),
        ),
    ]
