# Generated by Django 6.1.1 on 2026-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_prazo_dias_uteis_produto_quantidade_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Usado na cotação de frete (Melhor Envio)', null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Usado na cotação de frete (Melhor Envio)', null=True, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Usado na cotação de frete (Melhor Envio)', null=True, verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Usado na cotação de frete (Melhor Envio)', max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
    ]
