# Generated by Django 6.1.1 on 2026-09-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produto_dimensoes_frete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(help_text='CEP de onde saem os envios (ex.: 07094-000). Usado na cotação Melhor Envio.', max_length=9, verbose_name='CEP de origem')),
                ('endereco', models.CharField(help_text='Endereço completo exibido e de referência da origem.', max_length=255, verbose_name='Endereço da loja')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da loja',
                'verbose_name_plural': 'Configuração da loja',
            },
        ),
    ]
